//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Proyecto.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Bitacora
    {
        public int idBitacora { get; set; }
        public int idUsuario { get; set; }
        public string tipoModificacion { get; set; }
        public System.DateTime fecha { get; set; }
        public int idEstadoModificacion { get; set; }
    
        public virtual EstadoModificacion EstadoModificacion { get; set; }
        public virtual Usuario Usuario { get; set; }
    }
}
