//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Proyecto.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class DetalleCotizacion
    {
        public int idDetalleCotizacion { get; set; }
        public int idEncabezadoCotizacion { get; set; }
        public int idVehiculo { get; set; }
        public int cantidad { get; set; }
        public decimal porcentajeDescuento { get; set; }
        public decimal precio { get; set; }
        public decimal montoDescuento { get; set; }
        public decimal montoImpuesto { get; set; }
        public decimal montoTotal { get; set; }
    
        public virtual EncabezadoCotizacion EncabezadoCotizacion { get; set; }
        public virtual Vehiculo Vehiculo { get; set; }
    }
}
