//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Proyecto.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Distrito
    {
        public int idDistrito { get; set; }
        public int idCanton { get; set; }
        public int idProvincia { get; set; }
        public string descripcion { get; set; }
    
        public virtual Canton Canton { get; set; }
    }
}
