//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Proyecto.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class EncabezadoCotizacion
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public EncabezadoCotizacion()
        {
            this.DetalleCotizacions = new HashSet<DetalleCotizacion>();
        }
    
        public int idEncabezadoCotizacion { get; set; }
        public System.DateTime fechaCreacion { get; set; }
        public int idCliente { get; set; }
        public int idEmpleado { get; set; }
        public int numeroLineas { get; set; }
        public int idCampana { get; set; }
        public int idEstadoCotizacion { get; set; }
        public decimal subTotal { get; set; }
        public decimal montoDescuento { get; set; }
        public decimal impuestoVentas { get; set; }
        public decimal total { get; set; }
    
        public virtual Campana Campana { get; set; }
        public virtual Cliente Cliente { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DetalleCotizacion> DetalleCotizacions { get; set; }
        public virtual Empleado Empleado { get; set; }
        public virtual EstadoCotizacion EstadoCotizacion { get; set; }
    }
}
