//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Proyecto.UI.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Campana
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Campana()
        {
            this.EncabezadoCotizacion = new HashSet<EncabezadoCotizacion>();
        }
    
        public int idCampana { get; set; }
        [Required]
        [Display(Name ="Nombre para la campaña")]
        public int idTipoCampana { get; set; }
        [Required]
        public int idSede { get; set; }
        public int idEstadoCampana { get; set; }
        public string nombre { get; set; }
        public string descripcion { get; set; }
        public int idProvincia { get; set; }
        public int idCanton { get; set; }
        public System.DateTime fechaInicio { get; set; }
        public System.DateTime fechaFinal { get; set; }
        public decimal descuentoMinimo { get; set; }
        public decimal descuentoMaximo { get; set; }
        public int idEmpleadoCreador { get; set; }
        public Nullable<int> idEmpleadoAprobador { get; set; }
    
        public virtual Canton Canton { get; set; }
        public virtual Empleado Empleado { get; set; }
        public virtual Empleado Empleado1 { get; set; }
        public virtual EstadoCampana EstadoCampana { get; set; }
        public virtual Sede Sede { get; set; }
        public virtual TipoCampana TipoCampana { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EncabezadoCotizacion> EncabezadoCotizacion { get; set; }
    }
}
