//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Proyecto.UI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DetalleCotizacion
    {
        public int idDetalleCotizacion { get; set; }
        public int idEncabezadoCotizacion { get; set; }
        public int idVehiculo { get; set; }
        public int cantidad { get; set; }
        public decimal porcentajeDescuento { get; set; }
        public decimal precio { get; set; }
        public decimal montoDescuento { get; set; }
        public decimal montoImpuesto { get; set; }
        public decimal montoTotal { get; set; }
    
        public virtual EncabezadoCotizacion EncabezadoCotizacion { get; set; }
        public virtual Vehiculo Vehiculo { get; set; }
    }
}
