//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Proyecto.UI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EncabezadoCotizacion
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public EncabezadoCotizacion()
        {
            this.DetalleCotizacion = new HashSet<DetalleCotizacion>();
        }
    
        public int idEncabezadoCotizacion { get; set; }
        public System.DateTime fechaCreacion { get; set; }
        public int idCliente { get; set; }
        public int idEmpleado { get; set; }
        public int numeroLineas { get; set; }
        public int idCampana { get; set; }
        public int idEstadoCotizacion { get; set; }
        public decimal subTotal { get; set; }
        public decimal montoDescuento { get; set; }
        public decimal impuestoVentas { get; set; }
        public decimal total { get; set; }
    
        public virtual Campana Campana { get; set; }
        public virtual Cliente Cliente { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DetalleCotizacion> DetalleCotizacion { get; set; }
        public virtual Empleado Empleado { get; set; }
        public virtual EstadoCotizacion EstadoCotizacion { get; set; }
    }
}
