//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Proyecto.UI.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class RMClientEntity : DbContext
    {
        public RMClientEntity()
            : base("name=RMClientEntity")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Bitacora> Bitacora { get; set; }
        public virtual DbSet<Campana> Campana { get; set; }
        public virtual DbSet<Canton> Canton { get; set; }
        public virtual DbSet<Cliente> Cliente { get; set; }
        public virtual DbSet<Departamento> Departamento { get; set; }
        public virtual DbSet<DetalleCotizacion> DetalleCotizacion { get; set; }
        public virtual DbSet<Distrito> Distrito { get; set; }
        public virtual DbSet<Empleado> Empleado { get; set; }
        public virtual DbSet<EncabezadoCotizacion> EncabezadoCotizacion { get; set; }
        public virtual DbSet<EstadoCampana> EstadoCampana { get; set; }
        public virtual DbSet<EstadoCliente> EstadoCliente { get; set; }
        public virtual DbSet<EstadoCotizacion> EstadoCotizacion { get; set; }
        public virtual DbSet<EstadoEmpleado> EstadoEmpleado { get; set; }
        public virtual DbSet<EstadoProveedor> EstadoProveedor { get; set; }
        public virtual DbSet<EstadoSede> EstadoSede { get; set; }
        public virtual DbSet<EstadoUsuario> EstadoUsuario { get; set; }
        public virtual DbSet<Genero> Genero { get; set; }
        public virtual DbSet<Ocupacion> Ocupacion { get; set; }
        public virtual DbSet<Proveedor> Proveedor { get; set; }
        public virtual DbSet<Provincia> Provincia { get; set; }
        public virtual DbSet<Sede> Sede { get; set; }
        public virtual DbSet<TipoCampana> TipoCampana { get; set; }
        public virtual DbSet<TipoCliente> TipoCliente { get; set; }
        public virtual DbSet<TipoVehiculo> TipoVehiculo { get; set; }
        public virtual DbSet<Usuario> Usuario { get; set; }
        public virtual DbSet<Vehiculo> Vehiculo { get; set; }
        public virtual DbSet<vHistoricoCotizaciones> vHistoricoCotizaciones { get; set; }
    }
}
