//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Proyecto.UI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Vehiculo
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Vehiculo()
        {
            this.Cliente = new HashSet<Cliente>();
            this.DetalleCotizacion = new HashSet<DetalleCotizacion>();
        }
    
        public int idVehiculo { get; set; }
        public int idProveedor { get; set; }
        public int idTipoVehiculo { get; set; }
        public string codigo { get; set; }
        public string marca { get; set; }
        public string modelo { get; set; }
        public string parametroVersion { get; set; }
        public int annio { get; set; }
        public int cantidadDisponible { get; set; }
        public System.DateTime fechaIngreso { get; set; }
        public Nullable<System.DateTime> fechaSalida { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Cliente> Cliente { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DetalleCotizacion> DetalleCotizacion { get; set; }
        public virtual Proveedor Proveedor { get; set; }
        public virtual TipoVehiculo TipoVehiculo { get; set; }
    }
}
