//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Proyecto.UI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class vHistoricoCotizaciones
    {
        public int Número { get; set; }
        public System.DateTime Fecha_de_Creacion { get; set; }
        public string Cedula_Cliente { get; set; }
        public string Cedula_Empleado { get; set; }
        public string Campaña { get; set; }
        public string Estado { get; set; }
        public decimal subTotal { get; set; }
        public decimal Monto_Descuento { get; set; }
        public decimal Impuesto_Ventas { get; set; }
        public decimal Total { get; set; }
    }
}
