//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Proyecto.DAL
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class RMClient1 : DbContext
    {
        public RMClient1()
            : base("name=RMClient1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Bitacora> Bitacoras { get; set; }
        public virtual DbSet<Campana> Campanas { get; set; }
        public virtual DbSet<Canton> Cantons { get; set; }
        public virtual DbSet<Cliente> Clientes { get; set; }
        public virtual DbSet<Departamento> Departamentoes { get; set; }
        public virtual DbSet<DetalleCotizacion> DetalleCotizacions { get; set; }
        public virtual DbSet<Distrito> Distritoes { get; set; }
        public virtual DbSet<Empleado> Empleadoes { get; set; }
        public virtual DbSet<EncabezadoCotizacion> EncabezadoCotizacions { get; set; }
        public virtual DbSet<EstadoCampana> EstadoCampanas { get; set; }
        public virtual DbSet<EstadoCliente> EstadoClientes { get; set; }
        public virtual DbSet<EstadoCotizacion> EstadoCotizacions { get; set; }
        public virtual DbSet<EstadoEmpleado> EstadoEmpleadoes { get; set; }
        public virtual DbSet<EstadoProveedor> EstadoProveedors { get; set; }
        public virtual DbSet<EstadoSede> EstadoSedes { get; set; }
        public virtual DbSet<EstadoUsuario> EstadoUsuarios { get; set; }
        public virtual DbSet<Genero> Generoes { get; set; }
        public virtual DbSet<Ocupacion> Ocupacions { get; set; }
        public virtual DbSet<Proveedor> Proveedors { get; set; }
        public virtual DbSet<Provincia> Provincias { get; set; }
        public virtual DbSet<Sede> Sedes { get; set; }
        public virtual DbSet<TipoCampana> TipoCampanas { get; set; }
        public virtual DbSet<TipoCliente> TipoClientes { get; set; }
        public virtual DbSet<TipoVehiculo> TipoVehiculoes { get; set; }
        public virtual DbSet<Usuario> Usuarios { get; set; }
        public virtual DbSet<Vehiculo> Vehiculoes { get; set; }
    }
}
