//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Proyecto.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Campana
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Campana()
        {
            this.EncabezadoCotizacions = new HashSet<EncabezadoCotizacion>();
        }
    
        public int idCampana { get; set; }
        public int idTipoCampana { get; set; }
        public int idSede { get; set; }
        public int idEstadoCampana { get; set; }
        public string nombre { get; set; }
        public string descripcion { get; set; }
        public int idProvincia { get; set; }
        public int idCanton { get; set; }
        public System.DateTime fechaInicio { get; set; }
        public System.DateTime fechaFinal { get; set; }
        public decimal descuentoMinimo { get; set; }
        public decimal descuentoMaximo { get; set; }
        public int idEmpleadoCreador { get; set; }
        public Nullable<int> idEmpleadoAprobador { get; set; }
    
        public virtual Canton Canton { get; set; }
        public virtual Empleado Empleado { get; set; }
        public virtual Empleado Empleado1 { get; set; }
        public virtual EstadoCampana EstadoCampana { get; set; }
        public virtual Sede Sede { get; set; }
        public virtual TipoCampana TipoCampana { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EncabezadoCotizacion> EncabezadoCotizacions { get; set; }
    }
}
